(()=>{
const q=(s,r=document)=>r.querySelector(s), qa=(s,r=document)=>[...r.querySelectorAll(s)];
const text=(s,v,r=document)=>{const e=q(s,r);if(e)e.textContent=v};
const remove=(s,r=document)=>qa(s,r).forEach(e=>e.remove());
text('.hero-right p','Bac en Administration des Affaires – Marketing. Je combine contenu, recherche consommateur et exécution marketing.');
const work=q('#work');
if(work){
 text('.kicker','Projets sélectionnés / 01—04',work); text('.section-title','Quatre projets. Quatre angles.',work); text('.section-intro','Contenu IA, marque, recherche consommateur et activation.',work);
 const idx=q('.project-index',work);
 if(idx && !q('a[href="#nordik"]',idx)){const row=document.createElement('a');row.className='project-row';row.href='#nordik';row.innerHTML='<div class="num">01</div><h3>Nordik Coffee</h3><p>Création de contenu assistée par IA et adaptation multi-plateforme.</p><div class="arrow">↗</div>';idx.prepend(row)}
 if(idx)qa('.project-row',idx).forEach((r,i)=>{const n=q('.num',r);if(n)n.textContent=String(i+1).padStart(2,'0')});
}
if(!q('#nordik')){
 const sec=document.createElement('section');sec.className='section light case';sec.id='nordik';
 sec.innerHTML=`<div class="container"><div class="case-hero reveal"><div><div class="project-disclosure">Projet personnel — marque fictive</div><div class="case-number">01 / Création de contenu assistée par IA</div><h2>Nordik<br>Coffee</h2></div><p class="case-deck">Concevoir une campagne sociale cohérente et l’adapter à Instagram, TikTok/Reels et LinkedIn.</p></div><div class="nordik-media reveal"><figure><img src="nordik-instagram.webp" alt="Mockup Instagram Nordik Coffee"><figcaption>Instagram / notoriété</figcaption></figure><figure><img src="nordik-reel.webp" alt="Mockup TikTok et Reels Nordik Coffee"><figcaption>TikTok / Reels</figcaption></figure><figure><img src="nordik-linkedin.webp" alt="Mockup LinkedIn Nordik Coffee"><figcaption>LinkedIn / storytelling</figcaption></figure></div><div class="case-meta reveal"><div class="meta"><b>Objectif</b><span>Notoriété & acquisition</span></div><div class="meta"><b>Canaux</b><span>Instagram / TikTok / LinkedIn</span></div><div class="meta"><b>Rôle</b><span>Brief, prompts, contenu, adaptation</span></div><div class="meta"><b>Statut</b><span>Mockups de portfolio</span></div></div><div class="story reveal"><h3>Du brief<br>au contenu.</h3><div class="story-copy"><p>Positionnement, direction créative, prompting, génération des visuels et adaptation du message selon le canal.</p><div class="callout">L’IA est un outil de production : le brief, les choix créatifs et l’adaptation marketing restent dirigés.</div><p class="proof-note">Marque fictive. Les chiffres visibles dans les interfaces sont illustratifs.</p></div></div></div>`;
 const efc=q('#efc');if(efc)efc.before(sec);
 const st=document.createElement('style');st.textContent='.nordik-media{display:grid;grid-template-columns:1fr .9fr 1fr;gap:16px;margin:42px 0 24px;align-items:start}.nordik-media figure{margin:0;background:#111;border:1px solid var(--line);overflow:hidden}.nordik-media img{width:100%;height:auto;display:block}.nordik-media figcaption{padding:11px 13px;background:#fff;color:#777;font-size:10px;font-weight:900;letter-spacing:.12em;text-transform:uppercase}.nordik-media figure:nth-child(2){margin-top:36px}@media(max-width:800px){.nordik-media{grid-template-columns:1fr}.nordik-media figure:nth-child(2){margin-top:0}}';document.head.append(st)
}
const compactCase=(id,num,deck)=>{const s=q(id);if(!s)return;text('.case-number',num,s);text('.case-deck',deck,s)};
compactCase('#efc','02 / Projet entrepreneurial — De FTC à EFC','Développer une marque de boxe amateur crédible, distinctive et prête pour son lancement.');
compactCase('#samourai','03 / Recherche marketing','Transformer une problématique de billetterie en recherche consommateur et recommandations concrètes.');
compactCase('#cafe','04 / Marketing expérientiel','Imaginer une activation durable et mesurable pour faire découvrir Café William autrement.');
const efc=q('#efc');if(efc){const ps=qa('.story .story-copy > p',efc);if(ps[0])ps[0].textContent='Construire la crédibilité d’une nouvelle promotion sans historique d’événements ni audience installée.';if(ps[1])ps[1].remove();text('.story .callout','Positionnement : faire de l’amateurisme un niveau de compétition, pas un niveau de marque.',efc);remove('.story .role-strip',efc);remove('.story .proof-note',efc)}
const sam=q('#samourai');if(sam){const intro=q('.story .story-copy > p',sam);if(intro)intro.remove();const cards=qa('.research-card p',sam),vals=['Entrevues pour identifier motivations, prix et attentes.','100 réponses analysées pour valider les tendances.','Billetterie en ligne, promotions et priorité à Instagram.'];cards.forEach((p,i)=>{if(vals[i])p.textContent=vals[i]});remove('.story .role-strip',sam);text('.proof-note','Données du projet : 100 questionnaires, 85 % d’achat en ligne, 67 % Instagram.',sam)}
const cafe=q('#cafe');if(cafe){text('.coffee-copy p','Deux jours de dégustation, contenu social, influence et partenaires.',cafe);const ps=qa('.story .story-copy > p',cafe);if(ps[0])ps[0].textContent='Bar à café, DJ, dégustation, créateurs et sensibilisation au commerce équitable.';if(ps[1]&&!ps[1].classList.contains('proof-note'))ps[1].remove();text('.story .callout','Chaque activation doit attirer, faire essayer, créer du contenu ou faciliter la conversion.',cafe);remove('.story .role-strip',cafe);text('.proof-note','Budget et performances : objectifs de projet, pas résultats commerciaux réels.',cafe)}
const about=q('#about');if(about){const ps=qa('.about-copy > p',about);if(ps[0])ps[0].textContent='Formation en marketing et expérience client : je relie stratégie, contenu, terrain et mesure.';if(ps[1])ps[1].remove();const rows=qa('.trow p',about),v=['Marketing, recherche consommateur, stratégie et communication.','Service client, besoins et résolution de problèmes.','Coordination passagers et gestion d’imprévus.','Positionnement, lancement, partenaires et expérience.'];rows.forEach((p,i)=>{if(v[i])p.textContent=v[i]})}
const val=q('#valeur');if(val){text('.value-head p','Relier réflexion marketing, compréhension client et exécution.',val);const ps=qa('.value-card p',val),v=['Segmenter, positionner, prioriser.','Concept, contenu et storytelling.','Données, KPIs et recommandations.','Coordination et gestion d’imprévus.'];ps.forEach((p,i)=>{if(v[i])p.textContent=v[i]})}
})();